### ISSUE TITLE
CDT v4.0.0 demo prep

### ISSUE THREAD

**Issue by stephenpdeos** [AntelopeIO/cdt#138]
With our newly established Developer Office Hours, we'd like to demo ENF-owned developer tooling updates sooner and more frequently. Our first targeted demo will be a bit of catchup previewing the contents of CDT v4.0.0.

**Tasks**

- [ ] Align on demo agenda
- [ ] Assign agenda items
- [ ] Review prepped material prior to presentation

**Comment by larryk85** [comment]
Agenda for the demo:

1) It should showcase creating a simple hello world project and build it. I.e. use the init command, add app, and build commands.
Present the project.yaml at each phase and final build artifacts, wasm and abi files.

2) It should then showcase creating a more complex example with external and internal dependencies, my test repos larryk85/antler-proj-example2, hello and foo (they all have antler-proj based names to find them) showcase this.  antler-proj-foo is the root project that uses the other two as dependencies and nested dependencies.  There is no need to repeat the steps although you could remove the dependency for hello and add that dependency as part of the video to showcase how dependencies are handled.

As before present the project yaml between phases and final build artifacts.

3) If I can fix the issue with token in the next couple of days to give time for integration into this demo, then I would like for the last thing to showcase be creating a smart contract that does a token transfer and uses antler-proj-token as its dependency so people can see how that works.
Please see if we have documentation from Nathan James of how to write the C++ for creating the example for the token transfers, they are quite simple.  Let me know if that does not exist and I can show what to do.

**Comment by BenjaminGormanPMP** [comment]
Closed per discussion with @stephenpdeos/team on 5/04/23 stand-up. Demo available: https://github.com/AntelopeIO/cdt/releases/tag/v4.0.0-rc1
