### ISSUE TITLE
Unlink Antler From Build

### ISSUE THREAD

**Issue by ericpassmore** [AntelopeIO/cdt#206]
## Clean up and remove Antler features

```[tasklist]
### Tasks
- [ ] Antler Proj in https://github.com/AntelopeIO/cdt/pull/114
- [ ] Antler Run in https://github.com/AntelopeIO/cdt/pull/94
- [ ] CDT Macros related to Antler as specified in https://github.com/AntelopeIO/cdt/pull/87
```
