### ISSUE TITLE
IF Prototype Implementation in CDT

### ISSUE THREAD

**Issue by bhazzard** [AntelopeIO/cdt#245]
```[tasklist]
### Tasks
- [ ] https://github.com/AntelopeIO/cdt/issues/210
- [ ] https://github.com/AntelopeIO/cdt/issues/215
- [ ] https://github.com/AntelopeIO/cdt/issues/257
```
