### ISSUE TITLE
LLVM16: Tracking Migration Issues 

### ISSUE THREAD

**Issue by ericpassmore** [AntelopeIO/cdt#325]
```[tasklist]
### Tasks
- [ ] [Investigate Warning from unneeded capture #324](https://github.com/AntelopeIO/cdt/issues/324)
- [ ] [Investigate Change Static Assets in meta_refl #323](https://github.com/AntelopeIO/cdt/issues/323)
- [ ] [Investigate removing const from value_or #322](https://github.com/AntelopeIO/cdt/issues/322)
- [ ] [Investigate use of <set> in ABI #321](https://github.com/AntelopeIO/cdt/issues/321)
- [ ] [Investigate added string dereference](https://github.com/AntelopeIO/cdt/issues/320)
- [ ] [Investigate unneeded ldd/wasm/Driver.cpp updates](https://github.com/AntelopeIO/cdt/issues/319)
```
