### ISSUE TITLE
ANTLER Debug Environment

### ISSUE THREAD

**Issue by larryk85** [AntelopeIO/cdt#69]
This issue encapsulates over all of the tasks that are required to complete the ANTLER Debug Environment

By building upon our `native` test framework we have in CDT, we will create a new way to debug smart contracts in a few ways.  As we move into the future and move to technologies like NatiVM, then this type of system will be even better fitting.

- [ ] Compile smart contracts as a 'shared object' to be loaded by the 'runner' (extending the framework that exists with the native compilation system) #78 
- [ ] Build the runner (functionality and API described in the ANTLER Project Design document). #79
- [ ] Build the `leap` plugin to expose host functions as an API endpoint for the runner to utilize and to 'pause' and direct control flow for a designated action on an account.
- [ ] Add `LLDB` as a build dependency of CDT to be used by end-users to debug their code. #80
- [ ] Add `LLDB` python module for smart contract dev usage. #81
- [ ] Extend DUNE to use this new functionality.

**Comment by ericpassmore** [comment]
deprecating Antler closing issues as won't fix
