### ISSUE TITLE
ANTLER Testing Environment

### ISSUE THREAD

**Issue by larryk85** [AntelopeIO/cdt#70]
This issue encapsulates over all of the tasks that are required to complete the ANTLER Testing Environment
This task builds upon the work of #69 

- [ ] Extend the `native` test framework to still allow for overriding the host functions, but have them default to extern 'C' so the shared object can link to those in the runner. #82
- [ ] Create a C and a C++ set of wrappers and abstractions for testing. #83
- [ ] Extend the runner to allow for another type of shared object (test object) to be loaded and run against the system. #84
- [ ] Extend the runner to accept a WASM file for the smart contract to 'test' against.
- [ ] Create a C and C++ set of wrappers for this higher level of testing (building on some of the primitives defined above). #85
- [ ] Updates for DUNE to use this new functionality.
- [ ] Update eos-system-contracts to use these new frameworks.

**Comment by ericpassmore** [comment]
deprecating Antler closing issues as won't fix
