### ISSUE TITLE
ANTLER Build System

### ISSUE THREAD

**Issue by larryk85** [AntelopeIO/cdt#77]
- [ ] Creation of antler-build #68 
- [ ] Generation of base CMake #73
- [ ] Generation of CMake for dependencies #74
- [ ] Compile and Link core project #75
- [ ] Compile and Link tests #76
- [ ] Updates for DUNE to use antler-build
- [ ] Updates for eosio-lib to use antler-build
- [ ] Updates for eos-system-contracts to use antler-build

**Comment by stephenpdeos** [comment]
Closing this issue out upon next release of CDT, remaining bullets captured in other issues
